github: dakshrajput100
custom:
  - https://paypal.me/Dakshrajput1  # PayPal
  - https://www.paypal.com/ncp/payment/YNCXQT5SBLXTN
  - https://dakshrajput100.github.io/Payment-UPI_ID/     # UPI ID

    
